### ISSUE TITLE
Renaming Table Bug

### ISSUE THREAD

**Issue by ajette** [dbsteward/dbsteward#128]
Attempts to rename a table are met with errors when composting the XML. I am following examples in section 5 of https://github.com/dbsteward/dbsteward/blob/master/docs/XMLGUIDE.md.

Here is the

```xml
<dbsteward>
  <database>
    <role>
      <application>db_app</application>
      <owner>root</owner>
      <replication>replication</replication>
      <readonly>readonly</readonly>
    </role>
  </database>
  <schema name="public" owner="ROLE_OWNER">
    <table name="test_table" oldTableName="old_test_table" primaryKey="id" owner
="ROLE_OWNER">
      <column name="id" type="int" null="false"/>
      <column name="description" type="varchar(255)" null="false"/>
      <column name="group_id" type="int" null="false"/>
      <index name="description_group_idx" using="btree">
        <indexDimension name="description_dim">description</indexDimension>
        <indexDimension name="group_dim">group_id</indexDimension>
      </index>
    </table>
  </schema>
</dbsteward>
```

The command I run:
`# dbsteward --xml=basic.xml`

And the error I get is:
`oldTableName panic - old_schema public does not contain table named old_test_table`

**Comment by ajette** [comment]
The error appears to be tied specifically to using oldTableName without oldSchemaName. When this happens a sting of bad things happen in the code that rely on oldSchemaName being there. As long as oldSchemaName exists, and it's fine if oldSchemaName is the same as schemaName, everything works as expected.

**Comment by ajette** [comment]
See: https://github.com/dbsteward/dbsteward/pull/131

**Comment by nkiraly** [comment]
#131 documentation update takes care of this. thank you for the documentation update.
